### ISSUE TITLE
🐛 BUG: soften strict boot topology

### ISSUE THREAD

**Issue by khase** [geli-lms/geli#203]
At this time we have a strict boot topology for our system:
  Database -> API -> Frontend
each container strictly depends on the previous ones.
So if the Database isn't completely bootet while we are trying to start the API the API will fail it's own boot and so the Frontend won't come up ether.

In fact this already did happen (in an automatic deploy):
```
web-frontend_1  | 2017/09/18 17:19:40 [emerg] 1#1: host not found in upstream "api" in /etc/nginx/conf.d/project.conf:8
web-frontend_1  | nginx: [emerg] host not found in upstream "api" in /etc/nginx/conf.d/project.conf:8
api_1           | info: --> Server successfully started at port 80
api_1           |
api_1           | events.js:163
api_1           |       throw er; // Unhandled 'error' event
api_1           |       ^
api_1           | MongoError: failed to connect to server [db:27017] on first connect [MongoError: connect ECONNREFUSED 172.19.0.2:27017]
api_1           |     at Pool.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/topologies/server.js:328:35)
api_1           |     at emitOne (events.js:96:13)
api_1           |     at Pool.emit (events.js:191:7)
api_1           |     at Connection.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
api_1           |     at Object.onceWrapper (events.js:293:19)
api_1           |     at emitTwo (events.js:106:13)
api_1           |     at Connection.emit (events.js:194:7)
api_1           |     at Socket.<anonymous> (/usr/src/app/node_modules/mongodb-core/lib/connection/connection.js:177:49)
api_1           |     at Object.onceWrapper (events.js:293:19)
api_1           |     at emitOne (events.js:96:13)
api_1           |     at Socket.emit (events.js:191:7)
api_1           |     at emitErrorNT (net.js:1283:8)
api_1           |     at _combinedTickCallback (internal/process/next_tick.js:80:11)
api_1           |     at process._tickCallback (internal/process/next_tick.js:104:9)
```

Maybe we should consider changing this behaviour so that the processes itself wait until its dependencies are online?
At least the API shouldn't completly crash if the database isn't available at boot time.

**Comment by aeimer** [comment]
👍  We should wait like 2 Minutes, if then the containers aren't up => THROW AN ERROR
